from typing import Any, Dict, List, Optional
from datetime import datetime

def open_pst(path: str) -> PyStore: ...

class PyStore:
    def properties(self) -> PyStoreProperties: ...
    def root_hierarchy_table(self) -> PyTableContext: ...
    def unique_value(self) -> int: ...
    def open_folder(self, node_id_str: str) -> PyFolder: ...
    def open_message(self, node_id_str: str, prop_ids: Optional[List[int]] = None) -> PyMessage: ...
    def named_property_map(self) -> PyNamedPropertyMap: ...
    def search_update_queue(self) -> PySearchUpdateQueue: ...

class PyStoreProperties:
    def get(self, prop_id: int) -> Any: ...
    def iter(self) -> Dict[str, Any]: ...
    def record_key(self) -> bytes: ...
    def make_entry_id(self, node_id_str: str) -> Dict[str, Any]: ...
    def display_name(self) -> str: ...
    def ipm_sub_tree_entry_id(self) -> Dict[str, Any]: ...
    def ipm_wastebasket_entry_id(self) -> Dict[str, Any]: ...
    def finder_entry_id(self) -> Dict[str, Any]: ...

class PyFolder:
    def properties(self) -> PyFolderProperties: ...
    def hierarchy_table(self) -> Optional[PyTableContext]: ...
    def contents_table(self) -> Optional[PyTableContext]: ...
    def associated_table(self) -> Optional[PyTableContext]: ...

class PyFolderProperties:
    def get(self, prop_id: int) -> Any: ...
    def iter(self) -> Dict[str, Any]: ...
    def node_id(self) -> str: ...
    def display_name(self) -> str: ...
    def content_count(self) -> int: ...
    def unread_count(self) -> int: ...
    def has_sub_folders(self) -> bool: ...

class PyMessage:
    def properties(self) -> PyMessageProperties: ...
    def recipient_table(self) -> PyTableContext: ...
    def attachment_table(self) -> Optional[PyTableContext]: ...

class PyMessageProperties:
    def get(self, prop_id: int) -> Any: ...
    def iter(self) -> Dict[str, Any]: ...
    def message_class(self) -> str: ...
    def message_flags(self) -> int: ...
    def message_size(self) -> int: ...
    def message_status(self) -> int: ...
    def creation_time(self) -> datetime: ...
    def last_modification_time(self) -> datetime: ...
    def search_key(self) -> bytes: ...

class PyTableContext:
    def context(self) -> Dict[str, Any]: ...
    def rows_matrix(self) -> List[Dict[str, Any]]: ...
    def find_row(self, row_id: int) -> Dict[str, Any]: ...

class PyNamedPropertyMap:
    def properties(self) -> PyNamedPropertyMapProperties: ...

class PyNamedPropertyMapProperties:
    def get(self, prop_id: int) -> Any: ...
    def iter(self) -> Dict[str, Any]: ...
    def bucket_count(self) -> int: ...
    def stream_guid(self) -> List[str]: ...
    def stream_entry(self) -> List[Dict[str, Any]]: ...
    def stream_string(self) -> List[str]: ...

class PySearchUpdateQueue:
    def updates(self) -> List[Dict[str, Any]]: ...
